export const CHANGE_NAME_SIGN_IN = 'CHANGE_NAME_SIGN_IN';
export const CHANGE_NAME_SIGN_UP = 'CHANGE_NAME_SIGN_UP';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PSW1 = 'CHANGE_PSW1';
export const CHANGE_PSW2 = 'CHANGE_PSW2';

export const CANSEL_SIGN_IN = 'CANSEL_SIGN_IN';
export const CANSEL_SIGN_UP = 'CANSEL_SIGN_UP';

export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';

export const FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST';
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
export const FETCH_REGISTER_FAILURE = 'FETCH_REGISTER_FAILURE';

export const FETCH_LOGIN_GITHUB_REQUEST = 'FETCH_LOGIN_GITHUB_REQUEST';
export const FETCH_LOGIN_GITHUB_SUCCESS = 'FETCH_LOGIN_GITHUB_SUCCESS';
export const FETCH_LOGIN_GITHUB_FAILURE = 'FETCH_LOGIN_GITHUB_FAILURE';

export const FETCH_LOGIN_GOOGLE_REQUEST = 'FETCH_LOGIN_GOOGLE_REQUEST';
export const FETCH_LOGIN_GOOGLE_SUCCESS = 'FETCH_LOGIN_GOOGLE_SUCCESS';
export const FETCH_LOGIN_GOOGLE_FAILURE = 'FETCH_LOGIN_GOOGLE_FAILURE';

export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';

export const FETCH_LOGOUT_REQUEST = 'FETCH_LOGOUT_REQUEST';
export const FETCH_LOGOUT_SUCCESS = 'FETCH_LOGOUT_SUCCESS';
export const FETCH_LOGOUT_FAILURE = 'FETCH_LOGOUT_FAILURE';
