export const CHANGE_NAME_SIGN_IN = 'CHANGE_NAME_SIGN_IN';
export const CHANGE_NAME_SIGN_UP = 'CHANGE_NAME_SIGN_UP';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_1 = 'CHANGE_PASSWORD_1';
export const CHANGE_PASSWORD_2 = 'CHANGE_PASSWORD_2';

export const CANCEL_SIGN_IN = 'CANCEL_SIGN_IN';
export const CANCEL_SIGN_UP = 'CANCEL_SIGN_UP';

export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';

export const FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST';
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
export const FETCH_REGISTER_FAILURE = 'FETCH_REGISTER_FAILURE';

export const FETCH_SESSION_REQUEST = 'FETCH_SESSION_REQUEST';
export const FETCH_SESSION_SUCCESS = 'FETCH_SESSION_SUCCESS';
export const FETCH_SESSION_FAILURE = 'FETCH_SESSION_FAILURE';

export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';

export const FETCH_LOGOUT_REQUEST = 'FETCH_LOGOUT_REQUEST';
export const FETCH_LOGOUT_SUCCESS = 'FETCH_LOGOUT_SUCCESS';
export const FETCH_LOGOUT_FAILURE = 'FETCH_LOGOUT_FAILURE';

export const FETCH_LISTS_REQUEST = 'FETCH_LISTS_REQUEST';
export const FETCH_LISTS_SUCCESS = 'FETCH_LISTS_SUCCESS';
export const FETCH_LISTS_FAILURE = 'FETCH_LISTS_FAILURE';

export const FETCH_ADD_LIST_REQUEST = 'FETCH_ADD_LIST_REQUEST';
export const FETCH_ADD_LIST_SUCCESS = 'FETCH_ADD_LIST_SUCCESS';
export const FETCH_ADD_LIST_FAILURE = 'FETCH_ADD_LIST_FAILURE';

export const FETCH_EDIT_LIST_REQUEST = 'FETCH_EDIT_LIST_REQUEST';
export const FETCH_EDIT_LIST_SUCCESS = 'FETCH_EDIT_LIST_SUCCESS';
export const FETCH_EDIT_LIST_FAILURE = 'FETCH_EDIT_LIST_FAILURE';

export const FETCH_DELETE_LIST_REQUEST = 'FETCH_DELETE_LIST_REQUEST';
export const FETCH_DELETE_LIST_SUCCESS = 'FETCH_DELETE_LIST_SUCCESS';
export const FETCH_DELETE_LIST_FAILURE = 'FETCH_DELETE_LIST_FAILURE';

export const CHANGE_NEW_LIST_VALUE = 'CHANGE_NEW_LIST_VALUE';
export const CHANGE_CURRENT_LIST = 'CHANGE_CURRENT_LIST';


export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE';

export const FETCH_ADD_TODO_REQUEST = 'FETCH_ADD_TODO_REQUEST';
export const FETCH_ADD_TODO_SUCCESS = 'FETCH_ADD_TODO_SUCCESS';
export const FETCH_ADD_TODO_FAILURE = 'FETCH_ADD_TODO_FAILURE';

export const FETCH_EDIT_TODO_REQUEST = 'FETCH_EDIT_TODO_REQUEST';
export const FETCH_EDIT_TODO_SUCCESS = 'FETCH_EDIT_TODO_SUCCESS';
export const FETCH_EDIT_TODO_FAILURE = 'FETCH_EDIT_TODO_FAILURE';

export const FETCH_DELETE_TODO_REQUEST = 'FETCH_DELETE_TODO_REQUEST';
export const FETCH_DELETE_TODO_SUCCESS = 'FETCH_DELETE_TODO_SUCCESS';
export const FETCH_DELETE_TODO_FAILURE = 'FETCH_DELETE_TODO_FAILURE';

export const CHANGE_NEW_TODO_VALUE = 'CHANGE_NEW_TODO_VALUE';
export const CHANGE_CURRENT_TODO = 'CHANGE_CURRENT_TODO';

export const TOOGLE_TODO_STATE_REQUEST = 'TOOGLE_TODO_STATE_REQUEST';
export const TOOGLE_TODO_STATE_SUCCESS = 'TOOGLE_TODO_STATE_SUCCESS';
export const TOOGLE_TODO_STATE_FAILURE = 'TOOGLE_TODO_STATE_FAILURE';
