export const CHANGE_NAME_SIGN_IN = 'CHANGE_NAME_SIGN_IN';
export const CHANGE_NAME_SIGN_UP = 'CHANGE_NAME_SIGN_UP';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_1 = 'CHANGE_PASSWORD_1';
export const CHANGE_PASSWORD_2 = 'CHANGE_PASSWORD_2';

export const CANCEL_SIGN_IN = 'CANCEL_SIGN_IN';
export const CANCEL_SIGN_UP = 'CANCEL_SIGN_UP';

export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';

export const FETCH_REGISTER_REQUEST = 'FETCH_REGISTER_REQUEST';
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
export const FETCH_REGISTER_FAILURE = 'FETCH_REGISTER_FAILURE';

export const FETCH_SESSION_REQUEST = 'FETCH_SESSION_REQUEST';
export const FETCH_SESSION_SUCCESS = 'FETCH_SESSION_SUCCESS';
export const FETCH_SESSION_FAILURE = 'FETCH_SESSION_FAILURE';

export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';

export const FETCH_LOGOUT_REQUEST = 'FETCH_LOGOUT_REQUEST';
export const FETCH_LOGOUT_SUCCESS = 'FETCH_LOGOUT_SUCCESS';
export const FETCH_LOGOUT_FAILURE = 'FETCH_LOGOUT_FAILURE';
